class Settings:
    MAIN_STATUS = ""
    STATUS = "{artist} — {track}"
    CLIENT_ID = ""
    CLIENT_SECRET = ""
    REDIRECT_URI = "http://localhost:8888/callback"
    USERNAME = ""
    SCOPE = "user-read-playback-state user-library-read"
    VK_TOKEN= ""
    LANGUAGE = "RU"