class Settings:
    MAIN_STATUS = ""
    STATUS = "{artist} — {track}"
    CLIENT_ID = ""
    CLIENT_SECRET = ""
    REDIRECT_URI = "http://localhost:8888/callback"
    USERNAME = ""
    SCOPE = ""
    VK_TOKEN= ""
    LANGUAGE = ""